---
services:
  ################################################################
  # Postgresql database
  ################################################################
  postgres:
    image: postgres:15.8-alpine3.20
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volume/postgres/data:/var/lib/postgresql/data
      - ./docker-volume/db-dump:/db-dump
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ################################################################
  # Pgadmin serve UI for postgres
  ################################################################
  pgadmin:
    image: elestio/pgadmin:REL-8_11
    user: root
    container_name: pgadmin
    hostname: pgadmin
    ports:
      - "8081:80"
    volumes:
      - ./docker-volume/pgadmin/data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=postgres

  ################################################################
  # Redis
  ################################################################
  redis:
    image: redis:7.4.0-alpine3.20
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker-volume/redis/data:/data
    command: redis-server --requirepass redis
