#####################################
# Build Environment
#####################################
FROM node:22.19.0-alpine AS builder

WORKDIR /home/web/app
COPY ./package.json ./package-lock.json ./
RUN npm ci --omit=dev
COPY . .
RUN npm run build

#####################################
# Execution Environment
#####################################=
FROM nginx:1.28-alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /home/web/app/build /usr/share/nginx/html
EXPOSE 80
